= 致谢

我想对 Confluent 公司的员工表示敬意和感谢，他们不仅发明了 Apache Kafka，而且是最早一批真正理解事件驱动架构的人。Ben Stopford 是 Confluent 公司的首席技术专家，他为本书提供了充分且富有价值的反馈，我为此感到荣幸。K.Scott Morrison 是 PHEMI Systems 公司的首席技术官，他也为本书提供了有价值的见解、反馈和建议。我要感谢 Scott 和 Ben 为本书提供的帮助。作为最初的审校者和技术专家，他们帮助我改进想法，敦促我提升内容质量，阻止我传播错误信息，并帮助我讲好事件驱动架构的故事。

我也要感谢我的朋友 Justin Tokarchuk、Gary Graham 和 Nick Green，他们校对和编辑了我的很多草稿。跟 Scott 和 Ben 一样，他们帮我找出了草稿中的重大缺陷，给出了改进建议，并且提供了与本书内容相关的见解和个人经验。

我还要感谢 O'Reilly 的伙伴们为我提供了各种各样的帮助。在这段经历中，我与许多优秀的人共事。我要特别感谢本书的编辑 Corbin Collins，他支持我度过了许多艰难的时刻并帮助我跟上进度。在这个项目中，他是伟大的合作者，感谢他为支持我所做出的努力。

文字编辑 Rachel Monaghan 让我想起了自己的高中时代。那时，我的论文总被划上红线退回。我非常感激她的敏锐眼光和对英语的了解，是她使本书更易于阅读和理解。感谢你，Rachel。

Christopher Faucher 给予了我非常多的耐心，他为我提供了很棒的反馈，毫无怨言地容忍我在最后时刻对书的内容做出一些不寻常的改动。感谢你，Chris。

作为内容策略副总裁，Mike Loukides 是我在 O'Reilly 最早接触的一位联系人。当我带着冗长的写作提议找到他时，他耐心地与我探讨，帮我重新提炼要点和精炼内容，使之成为今天摆在你面前的这本书。我很感激他花时间与我一起工作，并推进这项工作。我已尽最大努力听从他的告诫，以避免出版一部篇幅堪比词典的著作。

致我的父母，感谢你们对我所写内容的赞赏，还要感谢你们给予我的爱和支持。我的父亲向我介绍了Marshall McLuhan，虽然我基本上没有读过他的作品，但我深深地认同他对媒介如何影响信息的评价，这也改变了我看待和评估系统架构的方式。

最后，感谢所有支持我和本书出版工作的人。许多人通过自己的方式来支持我，包括对话、博客文章、演示文稿、开源代码、轶事、个人经历、故事和想到哪儿就说到哪儿的抱怨。谢谢你们！

撰写本书，既有让我愉快的时候，也有让我沮丧的时候。曾经有很多次，我骂自己自讨苦吃，但谢天谢地，更多的时候，我为这项工作感到欣慰。亲爱的读者，希望本书能在某种程度上帮助你学习和成长。
